spring:
  kafka:
    bootstrap-servers: breisen.datamix.ovh:9093
    #
    #listener:
    #  ack-mode: manual
    #
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.enseirb.gl.vroumvroom.Truck
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

server:
  error:
    whitelabel:
      enabled: false