spring:
  kafka:
    bootstrap-servers: breisen.datamix.ovh:9093

    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.enseirb.bid.buyerpricer.model.AuctionEvent
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

server:
  error:
    whitelabel:
      enabled: false